jobs:
  include:
  - stage: deploy Angular
    language: node_js
    node_js:
    - '10.7.0'
    #cache:
     # yarn: true
      #directories:
       #- node_modules
    before_install: echo "npm test temporarily disabled"
    script:
      - bash ./deploy.sh
  - stage: deploy PHP
    language: php
    php:
    - 7.1
    cache:
      directories:
      - "$HOME/.composer/cache"
    before_install:
    - cd Slim
    - pwd
    - travis_retry composer self-update
    - openssl aes-256-cbc -K $encrypted_57e385864280_key -iv $encrypted_57e385864280_iv
      -in deploy_key.enc -out ./deploy_key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./deploy_key
    - echo -e "Host 108.167.188.84\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh-add ./deploy_key
    install:
    - travis_retry composer install --no-interaction --prefer-source
    deploy:
      provider: script
      skip_cleanup: true
      script: rsync -r -e  'ssh -i ./deploy_key -p 2222' --quiet --delete-after ./*
        jrpiresc@108.167.188.84:~/public_html/mais-fono-rest
      on:
        branch: master

